version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: KIII
#    ports:
#      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  app:
    image: kiii:latest
    container_name: kiii_container
    build:
      context: ./kol2022-g1
    depends_on:
      - db
    ports:
      - "9999:9999"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/KIII
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update